// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKkkStOfYWz0YEPyifFWzQJhIO9oBsI-k',
    appId: '1:1009339070051:web:5d3c7e2a00a22753f4ea56',
    messagingSenderId: '1009339070051',
    projectId: 'home-control-flutter',
    authDomain: 'home-control-flutter.firebaseapp.com',
    databaseURL: 'https://home-control-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'home-control-flutter.appspot.com',
    measurementId: 'G-CT7QB53V80',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZST71xR52UI8XMYPotql3r36jnDB4Qvc',
    appId: '1:1009339070051:android:8f841b3a48b7e88df4ea56',
    messagingSenderId: '1009339070051',
    projectId: 'home-control-flutter',
    databaseURL: 'https://home-control-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'home-control-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjkx1nh1EImksGjBz_vg24Ttp7Hz4dmu0',
    appId: '1:1009339070051:ios:e2ebcbc16701949af4ea56',
    messagingSenderId: '1009339070051',
    projectId: 'home-control-flutter',
    databaseURL: 'https://home-control-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'home-control-flutter.appspot.com',
    iosClientId: '1009339070051-nb61juejer0nivrt70hcnc8u39a89tu5.apps.googleusercontent.com',
    iosBundleId: 'com.example.authenFirebaseFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjkx1nh1EImksGjBz_vg24Ttp7Hz4dmu0',
    appId: '1:1009339070051:ios:e2ebcbc16701949af4ea56',
    messagingSenderId: '1009339070051',
    projectId: 'home-control-flutter',
    databaseURL: 'https://home-control-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'home-control-flutter.appspot.com',
    iosClientId: '1009339070051-nb61juejer0nivrt70hcnc8u39a89tu5.apps.googleusercontent.com',
    iosBundleId: 'com.example.authenFirebaseFlutter',
  );
}
