name: smarthome_byme
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Firebase
  firebase_core: ^1.20.0
  firebase_auth: ^3.6.2
  firebase_database: ^9.1.4
  firebase_storage: ^10.3.10
  # Bloc
  flutter_bloc: ^8.0.1
  # Utils
  equatable: null
  # Image
  flutter_svg: ^1.1.0
  # Router
  go_router: ^4.3.0
  # Validation
  email_validator: ^2.0.1
  # Ui
  flutter_switch: ^0.3.2
  contained_tab_bar_view: ^0.8.0
  flutter_ripple: ^0.0.3
  dropdown_button2: ^1.8.2
  # Wifi
  wifi_scan: ^0.3.0
  plugin_wifi_connect: ^1.0.2
  # Premision
  permission_handler: ^10.0.1
  # Storage
  shared_preferences: ^2.0.15
  flutter_secure_storage: ^6.0.0
  # UDP
  udp: ^5.0.3
  # Asset to abum
  image_picker: ^0.8.5+3
  # Language
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Auto gene
  freezed: ^2.0.5
  json_serializable: ^6.2.0
  build_runner: ^2.2.0

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/device/
    - assets/icons/navigation/

  fonts:
    - family: NotoSans
      fonts:
        # - asset: assets/fonts/NotoSants/NotoSans-Black.ttf
        # - asset: assets/fonts/NotoSants/NotoSans-BlackItalic.ttf
        #   style: italic
        - asset: assets/fonts/NotoSants/NotoSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/NotoSants/NotoSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/NotoSants/NotoSans-Light.ttf
          weight: 300
        - asset: assets/fonts/NotoSants/NotoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSants/NotoSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSants/NotoSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoSants/NotoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSants/NotoSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/NotoSants/NotoSans-Black.ttf
          weight: 900
flutter_intl:
  enabled: true
